### ISSUE TITLE
Issue w/ fresh clone of repository

### ISSUE THREAD

**Issue by localheinz** [researchgate/CodingDojo#7]
![screen shot 2013-09-21 at 1 34 37 pm](https://f.cloud.github.com/assets/605483/1185543/e0f8a4b4-22b1-11e3-9111-35dc56c450dd.png)

:poop: ?

**Comment by localheinz** [comment]
Not so sure whether umlauts and spaces within file names are a great idea, given that different OS have problems with them.

**Comment by peterjmag** [comment]
Looks like this is actually a bug with previous versions of git on Mac. The solution involves setting a global config option and cloning a fresh copy of the repository: http://stackoverflow.com/a/15553796/349353.

Note that you might not have to update git on your Mac like that answer suggests. For me, the config option alone fixed it. (Looks like it was fixed in both 1.7.10 as well, not just 1.8: http://stackoverflow.com/a/20325261/349353)

```
$ git --version
git version 1.7.12.4 (Apple Git-37)
```

**Comment by localheinz** [comment]
For me, the config option alone fixed it, too. Thanks, @peterjmag!
